import buildPage from '../utils';
import data from '../data';
import Head from 'next/head';
import Image from 'next/image';
import PageBuilder from '../components/PageBuilder/PageBuilder';
import styles from '../styles/Home.module.css';

/* import '../styles/scss/main';
 */

import type { NextPage } from 'next';

const Home: NextPage = () => {
  const page = buildPage(data);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className={styles.main}>
        <PageBuilder data={data} />{' '}
        {/*    <h1>Okunola Joshua &#123;</h1>
        <pre>
          &#x2f;&#x2f; Fullstack JS developer
          <br />
          &#x2f;&#x2f; Okunola_joshua@yahoo.com
          <br />
          &#x2f;&#x2f; Okunola_joshua@yahoo.com
        </pre> */}
      </main>
    </div>
  );
};

export default Home;
